---
#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

############################################
# Build & Deploy (beta and release)        #
############################################
name: 'Build & Deploy'

on:
  push:
    branches:
      - main
  release:
    # Want to run the automation when a release is published
    types: ['published']

permissions: read-all

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy_beta_to_npm:
    name: Deploy to NPM (beta)
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC (npm trusted publishers)
      contents: read
    environment:
      name: release
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6.1.0
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
          scope: nvuillam
      - run: npm ci
      - run: |
          git config --global user.name nvuillam
          git config --global user.email nicolas.vuillamy@gmail.com
      - run: BETAID="$(date -d @"$(git log -1 --pretty=%ct)" '+%Y%m%d%H%M')" && npm version prerelease --preid="beta-$BETAID"
        shell: bash
      - run: npm publish --tag beta

  deploy_release_to_npm:
    name: Deploy to NPM (release)
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC (npm trusted publishers)
      contents: read
    environment:
      name: release
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6.1.0
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
          scope: nvuillam
      - run: npm ci
      - run: |
          git config --global user.name nvuillam
          git config --global user.email nicolas.vuillamy@gmail.com
      - run: npm publish

  build_push_docker_beta:
    name: Build & Push Docker image (beta)
    if: ${{ github.event_name == 'push' }}
    needs: deploy_beta_to_npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment:
      name: release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get current date
        run: echo "BUILD_DATE=$(date -d @"$(git log -1 --pretty=%ct)" +'%Y-%m-%dT%H:%M:%SZ')" >> ${GITHUB_ENV}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64, linux/arm64
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REVISION=${{ github.sha }}
            BUILD_VERSION=beta
            NPM_GROOVY_LINT_VERSION=beta
          load: false
          push: true
          tags: |
            nvuillam/npm-groovy-lint:beta
            ghcr.io/nvuillam/npm-groovy-lint:beta

  build_push_docker_release:
    name: Build & Push Docker image (release)
    if: ${{ github.event_name == 'release' }}
    needs: deploy_release_to_npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment:
      name: release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get current date
        run: echo "BUILD_DATE=$(date -d @"$(git log -1 --pretty=%ct)" +'%Y-%m-%dT%H:%M:%SZ')" >> ${GITHUB_ENV}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          context: .
          file: Dockerfile
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REVISION=${{ github.sha }}
            BUILD_VERSION=${{ github.event.release.tag_name }}
            NPM_GROOVY_LINT_VERSION=latest
          load: false
          push: true
          tags: |
            nvuillam/npm-groovy-lint:${{ github.event.release.tag_name }}
            nvuillam/npm-groovy-lint:latest
            ghcr.io/nvuillam/npm-groovy-lint:${{ github.event.release.tag_name }}
            ghcr.io/nvuillam/npm-groovy-lint:latest
